model:
  base_learning_rate: 2.0e-5
  target: ldm.models.worm_latent_diffusion.WormMaskNativeDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    timesteps: 1000
    loss_type: l2
    first_stage_key: mask
    mask_key: mask
    image_size: 256
    channels: 1
    representation: sdf
    sdf_clip: 32.0
    x0_loss_weight: 0.1
    log_every_t: 200
    monitor: val/loss_simple_ema
    use_ema: true
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 256
        in_channels: 1
        out_channels: 1
        model_channels: 64
        attention_resolutions:
        - 16
        - 8
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_head_channels: 32
        use_checkpoint: true

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8
    wrap: false
    train:
      target: ldm.data.worm.WormPairsTrain
      params:
        root: data/worm
        size: 256
    validation:
      target: ldm.data.worm.WormPairsValidation
      params:
        root: data/worm
        size: 256

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 4
        latest_only: true
        log_validation_first_batch_only: true
        increase_log_steps: false
        log_images_kwargs:
          sample: true
          ddim_steps: 100
          ddim_eta: 0.0
          plot_diffusion_rows: false
          plot_progressive_rows: false
    metrics_over_trainsteps_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        filename: "{epoch:06}-{step:09}"
        verbose: true
        save_top_k: -1
        every_n_train_steps: 10000
        save_weights_only: true

  trainer:
    benchmark: true
    check_val_every_n_epoch: 10
