model:
  base_learning_rate: 8.0e-6
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l2
    first_stage_key: image_mask
    cond_stage_key: class_label
    image_size: 64
    channels: 4
    concat_mode: false
    conditioning_key: adm
    monitor: val/loss_simple_ema
    use_ema: true
    scale_by_std: true
    scale_factor: 0.20140717923641205
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 4
        out_channels: 4
        model_channels: 128
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32
        num_classes: 4
    first_stage_config:
      target: ldm.models.paired_autoencoder.WormLegacyJointAutoencoderKL
      params:
        image_key: image_mask
        embed_dim: 4
        ckpt_path: logs/autoencoder/joint-AE-original/last.ckpt
        log_binarized: true
        log_samples: false
        lossconfig:
          target: torch.nn.Identity
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 4
          out_ch: 4
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
    cond_stage_config:
      target: torch.nn.Identity
